server:
  AppVersion: 1.0.0
  Port: :5000
  Mode: Development
  Debug: false

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: info

postgres:
  PostgresqlHost: localhost
  PostgresqlPort: 5432
  PostgresqlUser: postgres
  PostgresqlPassword: postgres
  PostgresqlDbname: postgres
  PostgresqlSslmode: false
  PgDriver: pgx